<#
Set up or update one machine with the rules harness and the ping-personal plugin.
Re-run it to pick up future changes; a run with nothing new is a no-op PASS.

Usage:
  powershell -ExecutionPolicy Bypass -File "<repo>\scripts\bootstrap_machine.ps1" -RepoPath "<repo>"
  -RepoPath   folder for the ai-skills clone (or your fork). Example: C:\Users\<you>\src\ai-skills
  -RepoUrl    git URL to clone when -RepoPath has no clone yet. Example: https://github.com/<you>/ai-skills.git
  -SkipPlugin skip the Claude Code plugin install (used by the fresh-machine self-test)

Last line: MACHINE BOOTSTRAP PASS <plugin version> <CLAUDE.md sha256>, or a FAIL line and exit 1.
Windows PowerShell 5.1 compatible; ASCII only.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$RepoPath,
    [string]$RepoUrl = 'https://github.com/pchung1888/ai-skills.git',
    [switch]$SkipPlugin
)

# Native tools write progress to stderr; check $LASTEXITCODE instead of letting stderr throw.
$ErrorActionPreference = 'Continue'
$NoticePrefix = '<!-- Generated by scripts/sync_harness_adapters.py from harness/'
# Python's Path.home() reads USERPROFILE on Windows, so use the same home here.
$UserHome = $env:USERPROFILE

function Fail([string]$Message) {
    Write-Host "MACHINE BOOTSTRAP FAIL: $Message"
    exit 1
}

function Get-Sha256([string]$Path) {
    # .NET directly: Get-FileHash can be missing when a PowerShell 7 PSModulePath leaks into 5.1.
    if (-not (Test-Path -LiteralPath $Path)) { Fail "cannot hash missing file $Path" }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $digest = $sha.ComputeHash([System.IO.File]::ReadAllBytes($Path))
    } finally {
        $sha.Dispose()
    }
    return -join ($digest | ForEach-Object { $_.ToString('x2') })
}

# 1. Repository: clone if missing, else fast-forward only.
if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Fail 'git is not on PATH; install Git for Windows' }
if (-not (Test-Path -LiteralPath (Join-Path $RepoPath '.git'))) {
    Write-Host "Cloning $RepoUrl into $RepoPath"
    git clone $RepoUrl $RepoPath
    if ($LASTEXITCODE -ne 0) { Fail "git clone failed; check this machine can reach $RepoUrl" }
} else {
    git -C $RepoPath pull --ff-only
    if ($LASTEXITCODE -ne 0) { Fail "git pull --ff-only failed in $RepoPath (local changes or a diverged branch)" }
}

# 2. Python: a real interpreter, never the Microsoft Store alias.
$helper = Join-Path $RepoPath 'scripts\HarnessPython.ps1'
if (-not (Test-Path -LiteralPath $helper)) { Fail "missing $helper; is $RepoPath the ai-skills repo?" }
. $helper
$python = Find-HarnessPython
if (-not $python) { Fail 'Python 3.9 or newer not found (the Microsoft Store alias does not count); install it from python.org' }
Write-Host "Python: $python"

# 3. Install the harness adapters (first install backs up any existing CLAUDE.md / AGENTS.md).
$sync = Join-Path $RepoPath 'scripts\sync_harness_adapters.py'
$installOutput = (& $python $sync --install 2>&1 | Out-String)
Write-Host $installOutput.TrimEnd()
if ($LASTEXITCODE -ne 0 -or $installOutput -notmatch 'HARNESS ADAPTER INSTALL PASS') { Fail 'harness adapter install failed (see output above)' }

# 4. Verify the installed Claude adapter.
$claudeMd = Join-Path $UserHome '.claude\CLAUDE.md'
$staged = Join-Path $UserHome '.ping-harness\staging\claude-global.md'
if (-not (Test-Path -LiteralPath $claudeMd)) { Fail "$claudeMd was not created" }
$bytes = [System.IO.File]::ReadAllBytes($claudeMd)
foreach ($b in $bytes) { if ($b -ge 128) { Fail "$claudeMd contains a non-ASCII byte" } }
$firstLine = [System.Text.Encoding]::ASCII.GetString($bytes, 0, [Math]::Min($bytes.Length, $NoticePrefix.Length))
if ($firstLine -ne $NoticePrefix) { Fail "$claudeMd does not start with the generated notice" }
if ((Get-Sha256 $claudeMd) -ne (Get-Sha256 $staged)) { Fail "$claudeMd differs from the staged claude-global.md" }

# 5. Claude Code plugin: add the marketplace once, then install or update.
$version = 'plugin-skipped'
if (-not $SkipPlugin) {
    if (-not (Get-Command claude -ErrorAction SilentlyContinue)) { Fail 'the claude CLI is not on PATH; install Claude Code, then re-run' }
    $markets = (claude plugin marketplace list 2>&1 | Out-String)
    if ($markets -notmatch 'ping-personal') {
        claude plugin marketplace add pchung1888/ai-skills
        if ($LASTEXITCODE -ne 0) { Fail 'claude plugin marketplace add failed; check GitHub access' }
    } else {
        claude plugin marketplace update ping-personal
        if ($LASTEXITCODE -ne 0) { Fail 'claude plugin marketplace update ping-personal failed' }
    }
    $plugins = (claude plugin list --json 2>$null | Out-String) | ConvertFrom-Json
    $entry = @($plugins) | Where-Object { $_.id -eq 'ping-personal@ping-personal' } | Select-Object -First 1
    if ($entry) {
        claude plugin update ping-personal@ping-personal
    } else {
        claude plugin install ping-personal@ping-personal --scope user
    }
    if ($LASTEXITCODE -ne 0) { Fail 'claude plugin install/update of ping-personal@ping-personal failed' }
    $plugins = (claude plugin list --json 2>$null | Out-String) | ConvertFrom-Json
    $entry = @($plugins) | Where-Object { $_.id -eq 'ping-personal@ping-personal' } | Select-Object -First 1
    if (-not $entry) { Fail 'ping-personal@ping-personal is not listed after install' }
    $version = $entry.version
}

# 6. Codex: AGENTS.md is already installed by step 3; plugin registration stays manual.
if (Get-Command codex -ErrorAction SilentlyContinue) {
    Write-Host 'Codex: ~/.codex/AGENTS.md installed; enable the ping-personal plugin in ~/.codex/config.toml if not yet done'
} else {
    Write-Host 'SKIP: codex is not on PATH'
}

Write-Host "MACHINE BOOTSTRAP PASS $version $(Get-Sha256 $claudeMd)"
exit 0
