#!/usr/bin/env python3
"""Generate, stage, and atomically install harness adapters."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import shutil
import sys
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parent))
import harness_paths  # noqa: E402  (same folder; resolves source and state roots)

ROOT = Path(__file__).resolve().parents[1]
HOME = Path.home()
SOURCE_ROOT = harness_paths.source_root()
SOURCE_MANIFEST = SOURCE_ROOT / "manifest.json"
SHARED_PATH = SOURCE_ROOT / "core" / "shared.md"
CLAUDE_OVERLAY_PATH = SOURCE_ROOT / "runtime" / "claude.md"
CODEX_OVERLAY_PATH = SOURCE_ROOT / "runtime" / "codex.md"
CHATGPT_OVERLAY_PATH = SOURCE_ROOT / "runtime" / "chatgpt.md"
SOURCE_FILES = ("core/shared.md", "runtime/chatgpt.md", "runtime/claude.md", "runtime/codex.md")
STATE_ROOT = harness_paths.STATE_ROOT
INSTALL_STATE_PATH = STATE_ROOT / "install-state.json"
LEGACY_MANIFEST = STATE_ROOT / "manifest.json"
STAGING_ROOT = STATE_ROOT / "staging"
EXPORT_ROOT = STATE_ROOT / "exports"
CLAUDE_TARGET = HOME / ".claude" / "CLAUDE.md"
CODEX_TARGET = HOME / ".codex" / "AGENTS.md"
CUSTOM_EXPORT = EXPORT_ROOT / "chatgpt-custom-instructions.md"
PROJECT_EXPORT = EXPORT_ROOT / "chatgpt-project-brief.md"
SCANNER_PATH = (
    ROOT
    / "plugins"
    / "ping-personal"
    / "skills"
    / "personal-loop"
    / "lib"
    / "secrets_scan.py"
)
GENERATED_NOTICE = (
    "<!-- Generated by scripts/sync_harness_adapters.py from "
    "harness/ in the ai-skills repo. Edit the canonical source, not this file. -->\n\n"
)
# Text that only the shipped placeholder template carries; installing it would replace real rules.
TEMPLATE_MARKERS = ("TEMPLATE - edit before installing", "<your name>")
TRANSACTION_DIRNAME = "adapter-install-transaction"
TRANSACTION_VERSION = 1
TRANSACTION_FAULT_INJECTOR: Callable[[int, str, Path], None] | None = None


def fail(message: str) -> None:
    print(f"HARNESS ADAPTER SYNC FAIL: {message}")
    raise SystemExit(1)


def require(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="ascii"))
    except FileNotFoundError:
        fail(f"missing JSON file: {path}")
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON at {path}: {exc}")
    require(isinstance(data, dict), f"JSON root is not an object: {path}")
    return data


def read_ascii(path: Path) -> str:
    try:
        data = path.read_bytes()
    except FileNotFoundError:
        fail(f"missing canonical source: {path}")
    require(all(byte < 128 for byte in data), f"canonical source is not ASCII: {path}")
    return data.decode("ascii")


def encode_ascii(text: str, label: str) -> bytes:
    try:
        return text.encode("ascii")
    except UnicodeEncodeError as exc:
        fail(f"generated {label} is not ASCII: {exc}")


def source_records() -> dict[str, dict[str, object]]:
    records = {}
    for relative in SOURCE_FILES:
        data = (SOURCE_ROOT / relative).read_bytes()
        records[relative] = {"sha256": sha256_bytes(data), "size": len(data)}
    return records


def verify_sources() -> None:
    """Refuse to build adapters from sources that differ from the committed manifest."""
    manifest = load_json(SOURCE_MANIFEST)
    if manifest.get("schema_version") != 2:
        print("WARN: legacy source manifest; source hashes not verified")
        return
    recorded = manifest.get("sources")
    require(isinstance(recorded, dict) and set(recorded) == set(SOURCE_FILES), "source manifest lists the wrong files")
    for relative, actual in source_records().items():
        require(
            recorded[relative] == actual,
            f"{relative} differs from harness/manifest.json; review the edit, then run --update-manifest",
        )


def update_source_manifest() -> None:
    manifest = {"schema_version": 2, "sources": source_records()}
    atomic_write(SOURCE_MANIFEST, (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("ascii"))


def refuse_template_source() -> None:
    """Refuse to install the unfilled placeholder template over a machine's real rules."""
    shared = read_ascii(SHARED_PATH)
    found = [marker for marker in TEMPLATE_MARKERS if marker in shared]
    require(
        not found,
        f"{SHARED_PATH} is still the placeholder template ({', '.join(found)}); "
        "fill it in, or set PING_HARNESS_ROOT to the harness folder that holds your real rules",
    )


def load_secret_scanner():
    require(SCANNER_PATH.is_file(), f"hardened secret scanner is missing: {SCANNER_PATH}")
    spec = importlib.util.spec_from_file_location("harness_adapter_secrets", SCANNER_PATH)
    require(spec is not None and spec.loader is not None, "cannot load hardened secret scanner")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.scan


def extract_profile(shared: str) -> tuple[str, str]:
    name = re.search(r"(?m)^- \*\*Name:\*\*\s*(.+)$", shared)
    role = re.search(r"(?m)^- \*\*Role:\*\*\s*(.+)$", shared)
    require(name is not None, "shared core lacks Name")
    require(role is not None, "shared core lacks Role")
    return name.group(1).strip(), role.group(1).strip()


def build_custom_instructions(shared: str) -> str:
    name, role = extract_profile(shared)
    text = f"""# Personal instructions

I am {name}. {role}

Treat me as technically capable. Explain mechanisms in plain English without removing technical detail. For substantive answers: lead with the direct answer, explain why you chose that approach, and finish with a `## TL;DR` of at most five action-led lines. Skip those sections for quick factual answers.

Use ASCII punctuation only. Ask one clarifying question when a short mid-task reply is genuinely ambiguous.

Honesty is mandatory. Classify factual claims as EXTRACTED, INFERRED, SUGGESTION, or UNKNOWN. Never turn uncertainty into a plausible fact. Before claiming work is done, verify it at the layer of the claim and cite the evidence.

For engineering changes: read before editing, find callers before changing logic or signatures, preserve unrelated work, and verify after editing. Keep user-global facts separate from project facts. Put repeatable procedures in skills or workflows rather than bloating global memory.
"""
    require(len(text) <= 1500, f"ChatGPT Custom Instructions exceed 1500 characters ({len(text)})")
    return text


def compose_adapters() -> dict[str, bytes]:
    verify_sources()
    shared = read_ascii(SHARED_PATH).rstrip() + "\n"
    claude_overlay = read_ascii(CLAUDE_OVERLAY_PATH).rstrip() + "\n"
    codex_overlay = read_ascii(CODEX_OVERLAY_PATH).rstrip() + "\n"
    chatgpt_overlay = read_ascii(CHATGPT_OVERLAY_PATH).rstrip() + "\n"
    custom = build_custom_instructions(shared)
    project = GENERATED_NOTICE + shared + "\n" + chatgpt_overlay
    outputs = {
        "claude-global.md": encode_ascii(GENERATED_NOTICE + shared + "\n" + claude_overlay, "Claude adapter"),
        "codex-global.md": encode_ascii(GENERATED_NOTICE + shared + "\n" + codex_overlay, "Codex adapter"),
        "chatgpt-custom-instructions.md": encode_ascii(custom, "ChatGPT Custom Instructions"),
        "chatgpt-project-brief.md": encode_ascii(project, "ChatGPT Project brief"),
    }
    scan = load_secret_scanner()
    for label, data in outputs.items():
        hits = scan(data.decode("ascii"))
        require(not hits, f"hardened secret scanner blocked {label}: {hits}")
    return outputs


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    try:
        with temporary.open("wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        require(temporary.read_bytes() == data, f"temporary write verification failed: {path}")
        os.replace(temporary, path)
        require(path.read_bytes() == data, f"atomic replacement verification failed: {path}")
        fsync_directory(path.parent)
    finally:
        if temporary.exists():
            temporary.unlink()


def fsync_directory(path: Path) -> None:
    """Persist directory metadata where the host supports directory fsync."""
    try:
        descriptor = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(descriptor)
    except OSError:
        pass
    finally:
        os.close(descriptor)


def transaction_root() -> Path:
    staging = STAGING_ROOT.resolve()
    raw_root = STAGING_ROOT / TRANSACTION_DIRNAME
    require(not raw_root.is_symlink(), "transaction root cannot be a symbolic link")
    root = raw_root.resolve()
    require(root != staging and staging in root.parents, "transaction root escapes staging")
    return root


def transaction_path(relative: str) -> Path:
    require(isinstance(relative, str) and relative != "", "invalid transaction relative path")
    candidate_relative = Path(relative)
    require(not candidate_relative.is_absolute(), f"absolute transaction path rejected: {relative}")
    root = transaction_root()
    unresolved = root / candidate_relative
    cursor = root
    for part in candidate_relative.parts:
        cursor /= part
        require(not cursor.is_symlink(), f"symbolic-link transaction path rejected: {relative}")
    candidate = unresolved.resolve()
    require(root in candidate.parents, f"transaction path escapes staging: {relative}")
    return candidate


def transaction_journal_path() -> Path:
    return transaction_path("journal.json")


def transaction_targets() -> tuple[tuple[str, Path], ...]:
    return (
        ("claude", CLAUDE_TARGET),
        ("codex", CODEX_TARGET),
        ("chatgpt_custom_instructions", CUSTOM_EXPORT),
        ("chatgpt_project_brief", PROJECT_EXPORT),
        ("install_state", INSTALL_STATE_PATH),
    )


def remove_transaction_artifacts() -> None:
    root = transaction_root()
    journal = transaction_journal_path()
    if journal.exists():
        require(journal.is_file(), f"transaction journal is not a file: {journal}")
        journal.unlink()
        fsync_directory(journal.parent)
    if root.exists():
        require(root.is_dir(), f"transaction root is not a directory: {root}")
        shutil.rmtree(root)
        fsync_directory(root.parent)


def validate_transaction_replacements(replacements: list[tuple[str, Path, bytes]]) -> None:
    expected = transaction_targets()
    require(len(replacements) == len(expected), "transaction replacement count differs")
    for (name, path, data), (expected_name, expected_path) in zip(replacements, expected):
        require(name == expected_name, f"transaction replacement order differs: {name}")
        require(path.resolve() == expected_path.resolve(), f"transaction target differs: {name}")
        require(isinstance(data, bytes), f"transaction replacement is not bytes: {name}")


def prepare_transaction(replacements: list[tuple[str, Path, bytes]]) -> None:
    validate_transaction_replacements(replacements)
    root = transaction_root()
    journal_path = transaction_journal_path()
    require(not journal_path.exists(), f"transaction journal already exists: {journal_path}")
    if root.exists():
        require(root.is_dir(), f"transaction root is not a directory: {root}")
        shutil.rmtree(root)
    transaction_path("prestate").mkdir(parents=True, exist_ok=False)

    entries = []
    for index, (name, target, _) in enumerate(replacements):
        require(
            not target.exists() or (target.is_file() and not target.is_symlink()),
            f"transaction target is not a regular file: {target}",
        )
        existed = target.is_file()
        prestate = target.read_bytes() if existed else b""
        relative = f"prestate/{index:02d}-{name}.bin"
        prestate_path = transaction_path(relative)
        atomic_write(prestate_path, prestate)
        entries.append(
            {
                "name": name,
                "target": str(target.resolve()),
                "prestate": relative,
                "existed": existed,
                "sha256": sha256_bytes(prestate),
                "size": len(prestate),
            }
        )

    journal = {
        "version": TRANSACTION_VERSION,
        "state": "prepared",
        "entries": entries,
    }
    journal_bytes = (json.dumps(journal, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("ascii")
    atomic_write(journal_path, journal_bytes)


def load_transaction_prestate() -> list[tuple[str, Path, bool, bytes]]:
    journal_path = transaction_journal_path()
    require(journal_path.is_file(), f"transaction journal is missing: {journal_path}")
    journal = load_json(journal_path)
    require(journal.get("version") == TRANSACTION_VERSION, "transaction journal version differs")
    require(journal.get("state") == "prepared", "transaction journal state differs")
    raw_entries = journal.get("entries")
    expected = transaction_targets()
    require(isinstance(raw_entries, list), "transaction journal entries are not a list")
    require(len(raw_entries) == len(expected), "transaction journal entry count differs")

    validated = []
    for index, (raw, (expected_name, expected_target)) in enumerate(zip(raw_entries, expected)):
        require(isinstance(raw, dict), f"transaction journal entry is invalid: {index}")
        require(raw.get("name") == expected_name, f"transaction journal name differs: {index}")
        require(raw.get("target") == str(expected_target.resolve()), f"transaction journal target differs: {expected_name}")
        expected_relative = f"prestate/{index:02d}-{expected_name}.bin"
        require(raw.get("prestate") == expected_relative, f"transaction prestate path differs: {expected_name}")
        prestate_path = transaction_path(raw["prestate"])
        require(prestate_path.is_file(), f"transaction prestate is missing: {expected_name}")
        prestate = prestate_path.read_bytes()
        existed = raw.get("existed")
        size = raw.get("size")
        digest = raw.get("sha256")
        require(isinstance(existed, bool), f"transaction existed flag is invalid: {expected_name}")
        require(type(size) is int and size >= 0, f"transaction size is invalid: {expected_name}")
        require(isinstance(digest, str) and re.fullmatch(r"[0-9a-f]{64}", digest) is not None, f"transaction hash is invalid: {expected_name}")
        require(len(prestate) == size, f"transaction prestate size differs: {expected_name}")
        require(sha256_bytes(prestate) == digest, f"transaction prestate hash differs: {expected_name}")
        validated.append((expected_name, expected_target, existed, prestate))
    return validated


def recover_abandoned_transaction() -> bool:
    journal_path = transaction_journal_path()
    if not journal_path.exists():
        return False
    require(journal_path.is_file(), f"transaction journal is not a file: {journal_path}")

    prestates = load_transaction_prestate()
    for name, target, existed, prestate in prestates:
        if existed:
            atomic_write(target, prestate)
        elif target.exists():
            require(target.is_file(), f"transaction recovery target is not a file: {name}")
            target.unlink()
            fsync_directory(target.parent)

    for name, target, existed, prestate in prestates:
        if existed:
            require(target.is_file(), f"transaction recovery target is missing: {name}")
            require(target.read_bytes() == prestate, f"transaction recovery verification failed: {name}")
        else:
            require(not target.exists(), f"transaction recovery failed to remove new target: {name}")

    remove_transaction_artifacts()
    return True


def apply_transaction(
    replacements: list[tuple[str, Path, bytes]], *, recover_on_error: bool = True
) -> None:
    try:
        prepare_transaction(replacements)
        for boundary, (name, path, data) in enumerate(replacements, start=1):
            atomic_write(path, data)
            if TRANSACTION_FAULT_INJECTOR is not None:
                TRANSACTION_FAULT_INJECTOR(boundary, name, path)
        for name, path, data in replacements:
            require(path.read_bytes() == data, f"transaction commit verification failed: {name}")
        remove_transaction_artifacts()
    except BaseException:
        if recover_on_error and transaction_journal_path().exists():
            try:
                recover_abandoned_transaction()
            except BaseException as recovery_error:
                raise RuntimeError("transaction recovery failed; journal retained") from recovery_error
        raise


def load_install_state() -> dict | None:
    """Per-machine install record; seeded once from the pre-repo manifest on the old layout."""
    if INSTALL_STATE_PATH.is_file():
        return load_json(INSTALL_STATE_PATH)
    if LEGACY_MANIFEST.is_file():
        legacy = load_json(LEGACY_MANIFEST)
        seeded = {key: legacy[key] for key in ("backups", "installation") if key in legacy}
        if seeded:
            return seeded
    return None


def first_install_backup() -> dict:
    """Copy whatever adapters this machine already has before the first install overwrites them."""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backups = {}
    for runtime, target, filename in (
        ("claude", CLAUDE_TARGET, "claude-CLAUDE.md"),
        ("codex", CODEX_TARGET, "codex-AGENTS.md"),
    ):
        if not target.is_file():
            backups[runtime] = {"source": str(target), "existed": False}
            continue
        data = target.read_bytes()
        relative = f"backups/{stamp}/{filename}"
        atomic_write(STATE_ROOT / relative, data)
        backups[runtime] = {
            "source": str(target),
            "existed": True,
            "relative_path": relative,
            "bootstrap_source_sha256": sha256_bytes(data),
        }
        print(f"First install: backed up {target} to {STATE_ROOT / relative}")
    return {"backups": backups}


def backup_bytes(state: dict, runtime: str) -> bytes:
    record = state.get("backups", {}).get(runtime, {})
    relative = record.get("relative_path")
    require(isinstance(relative, str), f"install state lacks {runtime} backup path")
    path = (STATE_ROOT / relative).resolve()
    require(path.is_file(), f"missing {runtime} backup: {path}")
    data = path.read_bytes()
    require(sha256_bytes(data) == record.get("bootstrap_source_sha256"), f"{runtime} backup hash drift")
    return data


def verify_install_precondition(state: dict, outputs: dict[str, bytes]) -> None:
    installation = state.get("installation")
    if installation is None:
        for runtime, target in (("claude", CLAUDE_TARGET), ("codex", CODEX_TARGET)):
            record = state.get("backups", {}).get(runtime, {})
            if record.get("existed") is False:
                require(not target.exists(), f"{runtime} target appeared since the first-install backup")
                continue
            require(target.is_file(), f"{runtime} target disappeared since backup")
            require(target.read_bytes() == backup_bytes(state, runtime), f"{runtime} target drifted since backup")
        return
    targets = installation.get("targets", {})
    for name, path, output_key in (
        ("claude", CLAUDE_TARGET, "claude-global.md"),
        ("codex", CODEX_TARGET, "codex-global.md"),
    ):
        require(path.is_file(), f"{name} target is missing since the last install: {path}")
        expected_previous = targets.get(name, {}).get("sha256")
        require(expected_previous == sha256_bytes(path.read_bytes()), f"{name} target has manual drift")
        require(output_key in outputs, f"missing generated output: {output_key}")


def stage(outputs: dict[str, bytes]) -> None:
    STAGING_ROOT.mkdir(parents=True, exist_ok=True)
    for name, data in outputs.items():
        atomic_write(STAGING_ROOT / name, data)


def installation_targets(installed: dict[str, tuple[Path, bytes]]) -> dict[str, dict[str, object]]:
    return {
        name: {
            "path": str(path.resolve()),
            "sha256": sha256_bytes(data),
            "size": len(data),
        }
        for name, (path, data) in installed.items()
    }


def installation_is_current(manifest: dict, installed: dict[str, tuple[Path, bytes]], targets: dict[str, dict[str, object]]) -> bool:
    installation = manifest.get("installation")
    if not isinstance(installation, dict) or installation.get("targets") != targets:
        return False
    installed_at = installation.get("installed_at")
    if not isinstance(installed_at, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", installed_at):
        return False
    return all(path.is_file() and path.read_bytes() == data for path, data in installed.values())


def _install(outputs: dict[str, bytes], *, recover_on_error: bool) -> None:
    recover_abandoned_transaction()
    state = load_install_state()
    if state is None:
        state = first_install_backup()
    verify_install_precondition(state, outputs)
    stage(outputs)

    installed = {
        "claude": (CLAUDE_TARGET, outputs["claude-global.md"]),
        "codex": (CODEX_TARGET, outputs["codex-global.md"]),
        "chatgpt_custom_instructions": (CUSTOM_EXPORT, outputs["chatgpt-custom-instructions.md"]),
        "chatgpt_project_brief": (PROJECT_EXPORT, outputs["chatgpt-project-brief.md"]),
    }
    target_records = installation_targets(installed)
    if INSTALL_STATE_PATH.is_file() and installation_is_current(state, installed, target_records):
        return
    state["installation"] = {
        "installed_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "targets": target_records,
    }
    state_bytes = (json.dumps(state, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("ascii")
    replacements = [
        ("claude", CLAUDE_TARGET, outputs["claude-global.md"]),
        ("codex", CODEX_TARGET, outputs["codex-global.md"]),
        ("chatgpt_custom_instructions", CUSTOM_EXPORT, outputs["chatgpt-custom-instructions.md"]),
        ("chatgpt_project_brief", PROJECT_EXPORT, outputs["chatgpt-project-brief.md"]),
        ("install_state", INSTALL_STATE_PATH, state_bytes),
    ]
    apply_transaction(replacements, recover_on_error=recover_on_error)


def install(outputs: dict[str, bytes]) -> None:
    _install(outputs, recover_on_error=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--stage", action="store_true")
    mode.add_argument("--install", action="store_true")
    mode.add_argument(
        "--update-manifest",
        action="store_true",
        help="record the current source hashes in harness/manifest.json after a reviewed edit",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.update_manifest:
        update_source_manifest()
        print(f"HARNESS SOURCE MANIFEST UPDATED: {SOURCE_MANIFEST}")
        return 0
    if args.install:
        refuse_template_source()
    outputs = compose_adapters()
    stage(outputs)
    if args.install:
        install(outputs)
        print("HARNESS ADAPTER INSTALL PASS")
    else:
        print("HARNESS ADAPTER STAGE PASS")
    for name, data in sorted(outputs.items()):
        print(f"{name} bytes={len(data)} sha256={sha256_bytes(data)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
